// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package golog

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEadec542DecodeGithubComDnsoaGolog(in *jlexer.Lexer, out *logger) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEadec542EncodeGithubComDnsoaGolog(out *jwriter.Writer, in logger) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v logger) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEadec542EncodeGithubComDnsoaGolog(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v logger) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEadec542EncodeGithubComDnsoaGolog(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *logger) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEadec542DecodeGithubComDnsoaGolog(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *logger) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEadec542DecodeGithubComDnsoaGolog(l, v)
}
func easyjsonEadec542DecodeGithubComDnsoaGolog1(in *jlexer.Lexer, out *Logger) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.logger = new(logger)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEadec542EncodeGithubComDnsoaGolog1(out *jwriter.Writer, in Logger) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Logger) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEadec542EncodeGithubComDnsoaGolog1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Logger) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEadec542EncodeGithubComDnsoaGolog1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Logger) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEadec542DecodeGithubComDnsoaGolog1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Logger) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEadec542DecodeGithubComDnsoaGolog1(l, v)
}
func easyjsonEadec542DecodeGithubComDnsoaGolog2(in *jlexer.Lexer, out *Fields) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(Fields)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v1 interface{}
			if m, ok := v1.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := v1.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				v1 = in.Interface()
			}
			(*out)[key] = v1
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEadec542EncodeGithubComDnsoaGolog2(out *jwriter.Writer, in Fields) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v2Name))
			out.RawByte(':')
			if m, ok := v2Value.(easyjson.Marshaler); ok {
				m.MarshalEasyJSON(out)
			} else if m, ok := v2Value.(json.Marshaler); ok {
				out.Raw(m.MarshalJSON())
			} else {
				out.Raw(json.Marshal(v2Value))
			}
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Fields) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEadec542EncodeGithubComDnsoaGolog2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Fields) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEadec542EncodeGithubComDnsoaGolog2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Fields) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEadec542DecodeGithubComDnsoaGolog2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Fields) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEadec542DecodeGithubComDnsoaGolog2(l, v)
}
