name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go test -v -cover -race ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status $(go list ./... | grep -v /vendor/ | grep -v /explorer/idl/ | grep -v /api/idl/)

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          flag-name: Go-${{ matrix.os }}-${{ matrix.go-version }}
          parallel: true

  finish:
    needs: test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
